config/routes.rb
Rails.application.routes.draw do

  resources :photos, only: [:index]

  root 'search#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  rescue_from Flickr::ApiError, with: :render_not_found

  def index
    @photos = Flickr.photos.search(text: params[:q], sizes: true, sort: 'interestingness-desc', content_type: 1, page: params[:page], per_page: 30)
  end

  def render_not_found
    render nothing: true, status: 404
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/_addons.html.erb
<!-- web-based fonts -->
<link href='http://fonts.googleapis.com/css?family=Roboto:100,200,300,400,500,600,700,800,900' rel='stylesheet' type='text/css'>

<!-- Google Analytics -->
<!-- <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-0000000-0000', 'auto');
  ga('send', 'pageview');
</script> -->

app/views/layouts/_browser.html.erb
<!-- supports being stored on home screen (Android) -->
<meta name="mobile-web-app-capable" content="yes" />

<!-- supports being stored on home screen (Apple) -->
<meta name="apple-mobile-web-app-capable" content="yes" />

<!-- determining veiwport size for responsive design -->
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

<!-- render using latest version of IE -->
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

<!-- changes the color of the status bar (Apple) -->
<meta name="apple-mobile-web-app-status-bar-style" content="black" />

<!-- enables format detection of phone numbers -->
<meta name="format-detection" content="telephone=no" />

<!-- using respond.js to create polyfills from elements with specified dimensions -->
<!--[if lt IE 9]>
  <%= javascript_include_tag 'respond' %>
<![endif]-->

app/views/layouts/_footer.slim
footer
  .container-fluid
    .row
      .col-md-3
        .pull-left
          p
            | Made with ♥ by
            = link_to ' ben.gy', '//ben.gy'
            |  in Melbourne
      .col-md-6.text-center
        p
          strong Picturesque
          |  | Uncover the most engaging images on Flickr

      .col-md-3
        .pull-right
          p
            | Powered by
            = link_to ( image_tag ( 'flickr.png' ), class: 'responsive' ), '//flickr.com'

app/views/layouts/_header.slim
header
  nav.navbar.navbar-default.navbar-fixed-top role="navigation"
    .container-fluid
      .navbar-header
        button.navbar-toggle data-target="#navbar-collapse" data-toggle="collapse" type="button"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to root_path do
          .navbar-brand Picturesque

      #navbar-collapse.collapse.navbar-collapse
        ul.nav.navbar-nav.navbar-right
          li.navbar-form.nav-search
            = form_tag photos_path, method: :get do
              = text_field_tag :q, nil, id: 'search-field', class: 'placeholder-hide', size: 40, required: true, placeholder: "search again", onfocus: "this.placeholder=''", onblur: "this.placeholder='search again'", autocomplete: 'off'
              / = submit_tag 'Search', class: 'btn btn-lg btn-success'

app/views/layouts/_icons.html.erb
<!-- icon when website is saved to the home screen (Apple) -->
<!-- <link rel="apple-touch-icon" href="" /> -->
<!-- <link rel="apple-touch-icon" href=""  sizes="72x72" /> -->
<!-- <link rel="apple-touch-icon" href="" sizes="114x114" /> -->

<!-- icon when website is saved to the home screen (Android) -->
<!-- <link rel="icon" sizes="128x128" href="" /> -->
<!-- <link rel="icon" sizes="196x196" href="" /> -->

<!-- splash screen when loading site from home screen bookmark (Apple) -->
<!-- <link rel="apple-touch-startup-image" href="" sizes="320x460"  media="(max-device-width: 480px) and not (-webkit-min-device-pixel-ratio: 2)" /> -->
<!-- <link rel="apple-touch-startup-image" href="" sizes="640x920"  media="(max-device-width: 480px) and (-webkit-min-device-pixel-ratio: 2)" /> -->
<!-- <link rel="apple-touch-startup-image" href="" sizes="768x1004" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)" /> -->
<!-- <link rel="apple-touch-startup-image" href="" sizes="1024x748" media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)" /> -->

app/views/layouts/_metadata.html.erb
<title><%= Settings.project_name %> | <%= Settings.one_liner %></title>

<!-- General -->
<meta name="keywords"             content="<%= Settings.project_name %>, <%= Settings.keywords %>, <%= Settings.name %>">
<meta name="description"          content="<%= Settings.description %>">
<link rel="shortcut icon"         href="//<%= Settings.website %>/logo.png">
<link rel="image_src"             href="//<%= Settings.website %>/logo.png">
<link rel="canonical"             href="//<%= Settings.website %>"/>

<!-- Facebook -->
<meta property="og:image"         content="//<%= Settings.website %>/logo.png"/>
<meta property="og:url"           content="//<%= Settings.website %>"/>
<meta property="og:title"         content="<%= Settings.project_name %> | <%= Settings.one_liner %>"/>
<meta property="og:description"   content="<%= Settings.description %>"/>
<meta property="fb:admins"        content="<%= Settings.fb_admin %>"/>
<meta property="og:type"          content="website" />

<!-- Twitter -->
<meta name="twitter:card"         content="<%= Settings.project_name %> | <%= Settings.one_liner %>">
<meta name="twitter:site"         content="<%= Settings.twitter %>">
<meta name="twitter:title"        content="<%= Settings.project_name %> | <%= Settings.one_liner %>">
<meta name="twitter:description"  content="<%= Settings.description %>">
<meta name="twitter:creator"      content="<%= Settings.name %>">
<meta name="twitter:image:src"    content="//<%= Settings.website %>/logo.png">
<meta name="twitter:domain"       content="//<%= Settings.website %>">

<!-- Google+ -->
<meta itemprop="name"             content="<%= Settings.project_name %> | <%= Settings.one_liner %>">
<meta itemprop="description"      content="<%= Settings.description %>">
<meta itemprop="image"            content="//<%= Settings.website %>/logo.png">
<link rel="author"                href="//plus.google.com/<%= Settings.gp_admin %>"/>

app/views/layouts/application.slim
doctype html
| <!--[if lt IE 8]><html class="no-js preload lt-ie10 lt-ie9 lt-ie8 ie-suck"><![endif]-->
| <!--[if IE 8]><html class="no-js preload lt-ie10 lt-ie9 ie-8"><![endif]-->
| <!--[if IE 9]><html class="no-js preload lt-ie10 ie-9"><![endif]-->
| <!--[if gt IE 9]><!-->
html.no-js xml:lang="en" lang="en"
  | <!--<![endif]-->
  head
    = render 'layouts/metadata'
    = render 'layouts/icons'
    = render 'layouts/addons'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag :modernizr
    = render 'layouts/browser'
    = javascript_include_tag 'application'
    = growlyflash_static_notices
    = csrf_meta_tags
  body
    = yield
    / = render 'layouts/footer'

app/views/photos/index.slim
= render 'layouts/header'

.results

  #masonry.transitions-enabled
    - @photos.each do |photo|
      .box
        = link_to ( image_tag ( photo.medium(640).source_url ) ), photo.large1600_or_smaller.source_url

.text-center
  = will_paginate @photos, renderer: BootstrapPagination::Rails

app/views/search/index.slim
section#home.full-height
  .background.bg-image
  .container
    .search
      = form_tag photos_path, method: :get do
        = text_field_tag :q, nil, id: 'search-field', class: 'placeholder-hide', size: 40, required: true, placeholder: "search for images", onfocus: "this.placeholder=''", onblur: "this.placeholder='search for images'", autocomplete: 'off'
        / = submit_tag 'Search', class: 'btn btn-lg btn-success'

  = render 'layouts/footer'